config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :discount_campaigns
  resources :discounts
  resources :products, only: [:show, :index]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'increase_count/:product_id', to: 'carts#increase_count', as: :increase_count_in
    put 'decrease_count/:product_id', to: 'carts#decrease_count', as: :decrease_count_in
  end

  root to: 'products#index'
end

app/models/discount_campaign.rb
class DiscountCampaign < ActiveRecord::Base
  belongs_to :discount
  belongs_to :product
end

app/controllers/discount_campaigns_controller.rb
class DiscountCampaignsController < ApplicationController
  before_action :set_discount_campaign, only: [:show, :edit, :update, :destroy]

  # GET /discount_campaigns
  # GET /discount_campaigns.json
  def index
    @discount_campaigns = DiscountCampaign.all
  end

  # GET /discount_campaigns/1
  # GET /discount_campaigns/1.json
  def show
  end

  # GET /discount_campaigns/new
  def new
    @discount_campaign = DiscountCampaign.new
  end

  # GET /discount_campaigns/1/edit
  def edit
  end

  # POST /discount_campaigns
  # POST /discount_campaigns.json
  def create
    @discount_campaign = DiscountCampaign.new(discount_campaign_params)

    respond_to do |format|
      if @discount_campaign.save
        format.html { redirect_to @discount_campaign, notice: 'Discount campaign was successfully created.' }
        format.json { render :show, status: :created, location: @discount_campaign }
      else
        format.html { render :new }
        format.json { render json: @discount_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discount_campaigns/1
  # PATCH/PUT /discount_campaigns/1.json
  def update
    respond_to do |format|
      if @discount_campaign.update(discount_campaign_params)
        format.html { redirect_to @discount_campaign, notice: 'Discount campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @discount_campaign }
      else
        format.html { render :edit }
        format.json { render json: @discount_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discount_campaigns/1
  # DELETE /discount_campaigns/1.json
  def destroy
    @discount_campaign.destroy
    respond_to do |format|
      format.html { redirect_to discount_campaigns_url, notice: 'Discount campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discount_campaign
      @discount_campaign = DiscountCampaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discount_campaign_params
      params.require(:discount_campaign).permit(:name, :description, :discount_id, :product_id)
    end
end

app/helpers/discount_campaigns_helper.rb
module DiscountCampaignsHelper
end

app/views/discount_campaigns/_form.html.haml
= form_for(@discount_campaign) do |f|
  - if @discount_campaign.errors.any?
    #error_explanation
      %h2
        = pluralize(@discount_campaign.errors.count, "error")
        prohibited this discount_campaign from being saved:
      %ul
        - @discount_campaign.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :discount_id
    %br/
    = f.text_field :discount_id
  .field
    = f.label :product_id
    %br/
    = f.text_field :product_id
  .actions
    = f.submit

app/views/discount_campaigns/edit.html.haml
%h1 Editing Discount Campaign
= render 'form'
= link_to 'Show', @discount_campaign
|
= link_to 'Back', discount_campaigns_path

app/views/discount_campaigns/index.html.haml
%p#notice= notice
%h1 Listing Discount Campaigns
%table
  %thead
    %tr
      %th Name
      %th Description
      %th Discount
      %th Product
      %th{:colspan => "3"}
  %tbody
    - @discount_campaigns.each do |discount_campaign|
      %tr
        %td= discount_campaign.name
        %td= discount_campaign.description
        %td= discount_campaign.discount
        %td= discount_campaign.product
        %td= link_to 'Show', discount_campaign
        %td= link_to 'Edit', edit_discount_campaign_path(discount_campaign)
        %td= link_to 'Destroy', discount_campaign, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Discount campaign', new_discount_campaign_path

app/views/discount_campaigns/new.html.haml
%h1 New Discount Campaign
= render 'form'
= link_to 'Back', discount_campaigns_path

app/views/discount_campaigns/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @discount_campaign.name
%p
  %strong Description:
  = @discount_campaign.description
%p
  %strong Discount:
  = @discount_campaign.discount
%p
  %strong Product:
  = @discount_campaign.product
= link_to 'Edit', edit_discount_campaign_path(@discount_campaign)
|
= link_to 'Back', discount_campaigns_path