config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :discount_campaigns
  resources :discounts
  resources :products, only: [:show, :index]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'increase_count/:product_id', to: 'carts#increase_count', as: :increase_count_in
    put 'decrease_count/:product_id', to: 'carts#decrease_count', as: :decrease_count_in
  end

  root to: 'products#index'
end

app/models/discount.rb
class Discount < ActiveRecord::Base
  belongs_to :category
  has_many :discount_campaigns
  has_many :products, through: :discount_campaigns

  def calculate_discount(price)
    if is_percentage?
      price.to_f/100 * value_in_decimal
    else
      value_in_numbers
    end
  end
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  before_action :set_discount, only: [:show, :edit, :update, :destroy]

  # GET /discounts
  # GET /discounts.json
  def index
    @discounts = Discount.all
  end

  # GET /discounts/1
  # GET /discounts/1.json
  def show
  end

  # GET /discounts/new
  def new
    @discount = Discount.new
  end

  # GET /discounts/1/edit
  def edit
  end

  # POST /discounts
  # POST /discounts.json
  def create
    @discount = Discount.new(discount_params)

    respond_to do |format|
      if @discount.save
        format.html { redirect_to @discount, notice: 'Discount was successfully created.' }
        format.json { render :show, status: :created, location: @discount }
      else
        format.html { render :new }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discounts/1
  # PATCH/PUT /discounts/1.json
  def update
    respond_to do |format|
      if @discount.update(discount_params)
        format.html { redirect_to @discount, notice: 'Discount was successfully updated.' }
        format.json { render :show, status: :ok, location: @discount }
      else
        format.html { render :edit }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discounts/1
  # DELETE /discounts/1.json
  def destroy
    @discount.destroy
    respond_to do |format|
      format.html { redirect_to discounts_url, notice: 'Discount was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discount
      @discount = Discount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discount_params
      params.require(:discount).permit(:value_in_numbers, :value_in_decimal)
    end
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/views/discounts/_form.html.haml
= form_for(@discount) do |f|
  - if @discount.errors.any?
    #error_explanation
      %h2
        = pluralize(@discount.errors.count, "error")
        prohibited this discount from being saved:
      %ul
        - @discount.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :value_in_numbers
    %br/
    = f.text_field :value_in_numbers
  .field
    = f.label :value_in_decimal
    %br/
    = f.text_field :value_in_decimal
  .actions
    = f.submit

app/views/discounts/edit.html.haml
%h1 Editing Discount
= render 'form'
= link_to 'Show', @discount
|
= link_to 'Back', discounts_path

app/views/discounts/index.html.haml
%p#notice= notice
%h1 Listing Discounts
%table
  %thead
    %tr
      %th Value in numbers
      %th Value in decimal
      %th{:colspan => "3"}
  %tbody
    - @discounts.each do |discount|
      %tr
        %td= discount.value_in_numbers
        %td= discount.value_in_decimal
        %td= link_to 'Show', discount
        %td= link_to 'Edit', edit_discount_path(discount)
        %td= link_to 'Destroy', discount, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Discount', new_discount_path

app/views/discounts/new.html.haml
%h1 New Discount
= render 'form'
= link_to 'Back', discounts_path

app/views/discounts/show.html.haml
%p#notice= notice
%p
  %strong Value in numbers:
  = @discount.value_in_numbers
%p
  %strong Value in decimal:
  = @discount.value_in_decimal
= link_to 'Edit', edit_discount_path(@discount)
|
= link_to 'Back', discounts_path