config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :discount_campaigns
  resources :discounts
  resources :products, only: [:show, :index]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'increase_count/:product_id', to: 'carts#increase_count', as: :increase_count_in
    put 'decrease_count/:product_id', to: 'carts#decrease_count', as: :decrease_count_in
  end

  root to: 'products#index'
end

app/views/layouts/_messages.html.haml
%div{:class => "messages"}
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
        = content_tag :div, msg
        %a.close{:href => "#"} ×

app/views/layouts/_navigation.html.haml
%nav.menu
  %h1.name
    %i.fi-widget>
    Redis cart shop
  %ul.inline-list
    %li= link_to 'Home', root_path
  %ul.inline-list.hide-for-small-only.account-action
    = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
  %li
    = link_to cart_path do
      %i.fi-shopping-cart
      My Cart (
      %span.cart-count>= current_user.cart_count
      )
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path
- if user_signed_in?
  - if current_user.try(:admin?)
    %li= link_to 'Set discounts', discounts_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Shopping Cart"
    %meta{:content => "#{content_for?(:description) ? yield(:description) : "Shopping Cart"}", :name => "description"}/
    = stylesheet_link_tag 'application', media: 'all', "data-turbolinks-track" => true
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield